// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeTracker.Api.DatabaseConnection;

#nullable disable

namespace TimeTracker.Api.Migrations
{
    [DbContext(typeof(TimeTrackerContext))]
    [Migration("20250418045308_NewServer")]
    partial class NewServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TimeTracker.Api.Models.Activity", b =>
                {
                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstimatedTime")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ActivityId");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Activity");
                });

            modelBuilder.Entity("TimeTracker.Api.Models.Record", b =>
                {
                    b.Property<Guid>("RecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float?>("CurrentRunningTime")
                        .HasColumnType("real");

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RecordId");

                    b.HasIndex("ActivityId");

                    b.HasIndex("UserId");

                    b.ToTable("Record");
                });

            modelBuilder.Entity("TimeTracker.Api.Models.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RoleLevel")
                        .HasColumnType("int");

                    b.HasKey("RoleId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("TimeTracker.Api.Models.StatusLog", b =>
                {
                    b.Property<Guid>("StatusLogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StatusLogId");

                    b.HasIndex("RecordId");

                    b.ToTable("StatusLog");
                });

            modelBuilder.Entity("TimeTracker.Api.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("VerificationCode")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("TimeTracker.Api.Models.UserAssignment", b =>
                {
                    b.Property<Guid>("UserAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserAssignmentId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAssignment");
                });

            modelBuilder.Entity("TimeTracker.Api.Models.Activity", b =>
                {
                    b.HasOne("TimeTracker.Api.Models.User", "AssignedUser")
                        .WithMany("ActivityAssignedUsers")
                        .HasForeignKey("AssignedUserId")
                        .HasConstraintName("FK_Activity_User1");

                    b.HasOne("TimeTracker.Api.Models.User", "User")
                        .WithMany("ActivityUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Activity_User");

                    b.Navigation("AssignedUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimeTracker.Api.Models.Record", b =>
                {
                    b.HasOne("TimeTracker.Api.Models.Activity", "Activity")
                        .WithMany("Records")
                        .HasForeignKey("ActivityId")
                        .IsRequired()
                        .HasConstraintName("FK_Record_Activity");

                    b.HasOne("TimeTracker.Api.Models.User", "User")
                        .WithMany("Records")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Record_User");

                    b.Navigation("Activity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimeTracker.Api.Models.StatusLog", b =>
                {
                    b.HasOne("TimeTracker.Api.Models.Record", "Record")
                        .WithMany("StatusLogs")
                        .HasForeignKey("RecordId")
                        .IsRequired()
                        .HasConstraintName("FK_StatusLog_Record");

                    b.Navigation("Record");
                });

            modelBuilder.Entity("TimeTracker.Api.Models.UserAssignment", b =>
                {
                    b.HasOne("TimeTracker.Api.Models.Role", "Role")
                        .WithMany("UserAssignments")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_UserAssignment_Role");

                    b.HasOne("TimeTracker.Api.Models.User", "User")
                        .WithMany("UserAssignments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserAssignment_User");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimeTracker.Api.Models.Activity", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("TimeTracker.Api.Models.Record", b =>
                {
                    b.Navigation("StatusLogs");
                });

            modelBuilder.Entity("TimeTracker.Api.Models.Role", b =>
                {
                    b.Navigation("UserAssignments");
                });

            modelBuilder.Entity("TimeTracker.Api.Models.User", b =>
                {
                    b.Navigation("ActivityAssignedUsers");

                    b.Navigation("ActivityUsers");

                    b.Navigation("Records");

                    b.Navigation("UserAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
